# Servidor
server.port=8080

# Base de datos (usa variables de entorno)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/entretrazo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

